[package]
name        = "make"
version     = "4.4.1"
release     = 1
summary     = "GNU make build tool"
license     = "GPL-3.0"
source_url  = "https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz"
sha256      = "dd16fb1d67bfab79a72f5e8390735c49e3e8e70b4945a15ab1f81ddb78658fb3"
depends       = ["musl"]
build_depends = ["gcc"]
provides      = []
