[package]
name        = "wget"
version     = "1.24.5"
release     = 1
summary     = "Network utility to retrieve files from the web"
license     = "GPL-3.0"
source_url  = "https://ftp.gnu.org/gnu/wget/wget-1.24.5.tar.gz"
sha256      = "fa2dc35bab5184ecbc46a9ef83def2aaaa3f4c9f3c97d4bd19dcb07d4da3068c"
depends       = ["musl", "openssl", "zlib"]
build_depends = ["gcc", "make"]
provides      = []
