#!/bin/bash
# install.sh — post-install hook for glibc 2.42
# Runs AFTER the package files have been placed onto the filesystem.
set -euo pipefail

BUILD_DIR="$(pwd)/../glibc-build"

# ----- Install from the build directory -----
cd "$BUILD_DIR"

make DESTDIR="${MEOW_DESTDIR:-}" install

# ----- ldconfig -----
# Rebuild the shared-library cache so every program can find the new libc.
if command -v ldconfig &>/dev/null; then
    echo "Running ldconfig..."
    ldconfig
else
    echo "WARNING: ldconfig not found; skipping cache rebuild."
fi

# ----- /etc/ld.so.conf.d -----
# Ensure /usr/lib is listed in the dynamic linker search path.
LD_CONF_DIR="${MEOW_DESTDIR:-}/etc/ld.so.conf.d"
mkdir -p "$LD_CONF_DIR"
if [ ! -f "${LD_CONF_DIR}/glibc.conf" ]; then
    echo "/usr/lib" > "${LD_CONF_DIR}/glibc.conf"
    echo "Created ${LD_CONF_DIR}/glibc.conf"
fi

# ----- Timezone data -----
# Install a default UTC timezone symlink if none exists.
ZONEINFO_DIR="${MEOW_DESTDIR:-}/usr/share/zoneinfo"
LOCALTIME="${MEOW_DESTDIR:-}/etc/localtime"
if [ -d "$ZONEINFO_DIR" ] && [ ! -e "$LOCALTIME" ]; then
    ln -sf "$ZONEINFO_DIR/UTC" "$LOCALTIME"
    echo "Linked /etc/localtime -> UTC"
fi

# ----- nsswitch.conf -----
# Install a minimal nsswitch.conf if the system does not already have one.
NSSWITCH="${MEOW_DESTDIR:-}/etc/nsswitch.conf"
if [ ! -f "$NSSWITCH" ]; then
    cat > "$NSSWITCH" <<'EOF'
# /etc/nsswitch.conf — generated by glibc install hook
passwd:     files
group:      files
shadow:     files
hosts:      files dns
networks:   files
protocols:  files
services:   files
ethers:     files
rpc:        files
EOF
    echo "Installed minimal /etc/nsswitch.conf"
fi

echo "glibc post-install complete."
