[package]
name        = "binutils"
version     = "2.42"
release     = 1
summary     = "Assembler, linker and binary utilities"
license     = "GPL-3.0"
source_url  = "https://ftp.gnu.org/gnu/binutils/binutils-2.42.tar.xz"
sha256      = "f6e4d41fd5fc778b06b7891457b3620da5ecea1006c6a4a41ae998109f85a800"
depends       = ["musl", "zlib"]
build_depends = ["gcc", "make"]
provides      = []
