[package]
name        = "automake"
version     = "1.16.5"
release     = 1
summary     = "Generate Makefile.in files"
license     = "GPL-2.0"
source_url  = "https://ftp.gnu.org/gnu/automake/automake-1.16.5.tar.xz"
sha256      = "f01d58cd6d9d77fbdca9eb4bbd5ead1988228fdb73d6f7a201f5f8d6b118b469"
depends       = ["autoconf", "perl"]
build_depends = ["perl"]
provides      = []
