[package]
name        = "acl"
version     = "2.3.2"
release     = 1
summary     = "Access control list utilities"
license     = "LGPL-2.1"
source_url  = "https://download.savannah.gnu.org/releases/acl/acl-2.3.2.tar.xz"
sha256      = "597714c0c7d7fe78b9e09b4e1be9c1e24a6c9c5e6ee4eea65d49af3756e36a28"
depends       = ["musl", "attr"]
build_depends = ["gcc", "make", "attr"]
provides      = []
