[package]
name        = "diffutils"
version     = "3.10"
release     = 1
summary     = "GNU file comparison utilities"
license     = "GPL-3.0"
source_url  = "https://ftp.gnu.org/gnu/diffutils/diffutils-3.10.tar.xz"
sha256      = "90e5e93cc724e4ebe12ede80df1634063c7a855692685919bfe60b556c9bd09e"
depends       = ["musl"]
build_depends = ["gcc", "make"]
provides      = []
