# packages/nano/meowspec.toml
[package]
name        = "nano"
version     = "8.0"
release     = 1
summary     = "Small friendly text editor"
license     = "GPL-3.0"
source_url  = "https://www.nano-editor.org/dist/v8/nano-8.0.tar.xz"
sha256      = "c17f43fc0e37336b33ee50a209c701d5beb808adc2d9f089ca831b40539c9ac4"
depends       = ["musl", "ncurses"]
build_depends = ["gcc", "make", "ncurses-dev"]
